# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Branch Merge to Develop

on:
  push:
    branches:
      - "@langnang-temp/static"

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge Branch
        uses: devmasx/merge-branch@master
        with:
          from_branch: "@langnang-temp/static"
          target_branch: "develop"
          github_token: ${{ github.GITHUB_TOKEN }}
